### ISSUE TITLE
Pretrain code for 

### ISSUE THREAD

**Issue by YoungHS-NUS** [senmaoy/RAT-GAN#11]
Hi, I am following your works and I am wondering if you have the code for pre-training from the paper "3.1 Contrastive Text Embedding Pre-training". In the DAMSM.py file, I saw the CustomLSTM class and the  CNN_ENCODER class, I assume they are used to get the sentence-level feature s and the image-level f. I didn't find the pretraining part for the constrastive pre-training. If you have the code, would u mind sharing it? Thanks a lot!

**Comment by senmaoy** [comment]
Sure, I will upload the pre-training code for contrastive pre-trianing tommorow.

**Comment by senmaoy** [comment]
Pre-training code is now available at [here ](https://github.com/senmaoy/RAT-GAN/blob/main/code/pretrain_DAMSM.py)

**Comment by YoungHS-NUS** [comment]
Thanks a lot!!

**Comment by YoungHS-NUS** [comment]
Hi senmaoy, if you don't mind, can you also upload this part of the code?
`from miscc.losses import sent_loss, words_loss`
It would be of great help! Thanks a lot!

**Comment by senmaoy** [comment]
It's here[https://github.com/senmaoy/RAT-GAN/blob/main/code/miscc/losses.py](url)
