### ISSUE TITLE
birds image data链接失效

### ISSUE THREAD

**Issue by Amity8023** [senmaoy/RAT-GAN#13]
> README.md
> 2. Download the [birds](http://www.vision.caltech.edu/visipedia/CUB-200-2011.html) image data. Extract them to data/birds/.Raw text data of CUB dataset is avaiable [here](https://drive.google.com/file/d/1KyTQVo67izP4NEAAZBRnqrGG3yRh3azD/view?usp=sharing)

birds链接失效，新链接为 http://www.vision.caltech.edu/datasets/cub_200_2011/

**Comment by senmaoy** [comment]
666666666666666666666
