### ISSUE TITLE
Where to change to apply resume_epoch functionality from saved NetG and NetD models? 

### ISSUE THREAD

**Issue by AudityGhosh** [senmaoy/RAT-GAN#18]

**Comment by senmaoy** [comment]
for evaluation: https://github.com/senmaoy/RAT-GAN/blob/1e552d3f76fc9a176f21b4ec75b8568ab8ce5b8f/code/main.py#L59C18-L59C18

for training: load the pre-trained models from here: https://github.com/senmaoy/RAT-GAN/blob/1e552d3f76fc9a176f21b4ec75b8568ab8ce5b8f/code/main.py#L109
using netG.load_state_dict(torch.load('../models/%s/netG_500.pth'%(cfg.CONFIG_NAME)))
netD.load_state_dict(torch.load('../models/%s/netD_500.pth'%(cfg.CONFIG_NAME)))

**Comment by AudityGhosh** [comment]
Thank you very much, really grateful !
